## Basic Theme Info
name: WVU Design System
description: WVU Design System Theme

## Attributes, Data and Variables
custom_data_attributes:
  - alternate_url:
    title: Alternate URL
  - backpage_header:
    type: checkbox
    title: Remove header
  - blog_article_has_hero:
    type: checkbox
    title: If blog article, show hero
  - blog_index_hide_author:
    type: checkbox
    title: Hide blog index author?
  - breadcrumbs:
    type: checkbox
    title: Remove breadcrumbs
  - description:
    type: text
    rows: 6
    tile: Description
    required: false
    maxlength: 255
  - header_label:
    type: checkbox
    title: Show header label
  - header_subhead:
    type: checkbox
    title: Show header subhead
  - link_text:
    title: Link text
  - search_action:
    title: Search action
  - content_keys:
    title: Content Keys for Big Search
  - enable_keywords:
    type: checkbox
    title: Enable keywords?
  - thumbnail_alt:
    title: Thumbnail Alt Text
  - thumbnail_url:
    title: Thumnbail URL
  - thumbnail_url_sq:
    title: Thumnbail URL Square

custom_site_attributes:
  - apply_link_1
  - apply_link_1_url
  - apply_link_2
  - apply_link_2_url
  - apply_link_3
  - apply_link_3_url
  - classes_wvu_backpage_header
  - classes_wvu_backpage_header__h1
  - classes_wvu_breadcrumbs
  - classes_wvu-footer-links
  - co_brand_subtitle
  - default_content_01
  - default_content_02
  - default_content_03
  - disable_component_styler
  - disable_primary_nav
  - emergency_alert_json_url
  - facebook_url
  - flickr_url
  - github_url
  - google_site_verification
  - has_alternate_logo
  - has_co_brand
  - has_standard_footer
  - instagram_url
  - is_demo_site
  - linkedin_url
  - masthead_college_link_address
  - masthead_college_link_title
  - masthead_color
  - masthead_link_2_address
  - masthead_link_2_title
  - masthead_logo_url
  - masthead_title
  - nav_dropdowns
  - syndication_url
  - show_apply_links
  - show_instructions
  - sidebar_sticky_site
  - slot_00_masthead
  - slot_00_nav
  - twitter_handle
  - twitter_url
  - twitter_widget_id
  - youtube_url

## Template Config
# Specify which templates show up by default when creating a page
default_templates:
  content: backpage
  blog: blog_index
  article: blog_article
  error: error

## Optimizations
css:
  # Turn CSS compression on/off.
  compress: true
js:
  # Turn JavaScript compression and mangling on/off
  compress: true
  mangle: true
